import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideNavBar from "@/components/SideNavBar/SideNavBar";
import MobileNavBar from "@/components/MobileNavBar/MobileNavBar";
import Banner from "@/components/Banner/Banner";
export const inter = localFont({
  src: "../../public/fonts/Inter/Inter-VariableFont_slnt,wght.ttf",
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="root">
        <Banner />
        <MobileNavBar />
        <SideNavBar />
        {children}
      </body>
    </html>
  );
}
