name: Rebuild YABC Washington Irving Site
run-name: ${{ github.actor }} is rebuilding the site 🚀
on:
  push:
    branches:
      - main
jobs:
  Rebuild-Site:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      SPACE_KEY: ${{ secrets.SPACE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.0'
      - run: npm ci
      - run: npm run build
        env:
          API_KEY: ${{ env.API_KEY }}
          SPACE_KEY: ${{ env.SPACE_KEY }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: out/
  upload:
    needs: Rebuild-Site
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: out
          path: out
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Upload assets to Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        with:
          path: out
          destination: ${{ secrets.GCS_BUCKET }}
          glob: '*'

